use_frameworks!
source 'ssh://git@gitlab.263nt.com:2200/italkbbspecs/italkbbspecs.git' # new gitlab
source 'https://github.com/CocoaPods/Specs.git'  # 官方库

platform :ios, '9.0'

target 'AJSDKBox_Example' do
  pod 'AJSDKBox', :path => '../'

#  pod 'AJSDKBox/AJEZVIZ',:path => '../'
#  pod 'AJSDKBox/AJTuya', :path => '../'
#  pod 'AJSDKInterface', :path => '../'

  target 'AJSDKBox_Tests' do
    inherit! :search_paths

    
  end
end
